---
title: "K1_HMM"
output: html_document
date: "2026-04-01"
---

The objective of this analysis is to construct a high-quality HMM model
for M1 a, b and g regions.


>kt;M1;Monosporozyma_unispora;CAL9731056.1
MFFSLPIQKEIANHTIMKVNLLNLLCLTSVVSASFPYYDTIHLGLSALYAYFEPNSPIAVKIAFWGSFVEALDCTLDKAI
DVCIACEAKHEEPKWDCTRASKDLGISVVKNAISLYVGWQHAGTPNGSLEGQDTTALKKRSIARHCMSDEGYDHSCVSSW
LSDHYRDGMVTGWHEVSYPFVKRDNELPNIYVKNNETGISYHLIFNPASETNGAIAMSVVGNSNSSIGLMKRSNNYPIYA
PLCDSYIALDYCANQSKWAGIYQSGELTNMLEELLQNDVNGGWKSDFYKMYTIQENGKDQDWEISWRMYLAHAGNWIHWT
QCDTGY

Predicted cutsite from SignalP

```
# SignalP-6.0	Organism: Eukarya	Timestamp: 20260401185641
# ID	Prediction	OTHER	SP(Sec/SPI)	CS Position
Sequence	SP	0.000185	0.999825	CS pos: 33-34. Pr: 0.9825
```

>MuM1_Signal
MFFSLPIQKEIANHTIMKVNLLNLLCLTSVVSA
>MuM1_Alpha
SFPYYDTIHLGLSALYAYFEPNSPIAVKIAFWGSFVEALDCTLDKAIDVCIACEAKHEEPKWDCTRASKDLGISVVKNAISLYVGWQHAGTPNGSLEGQDTTALK
>MuM1_Gamma
KRSIARHCMSDEGYDHSCVSSWLSDHYRDGMVTGWHEVSYPFV
>MuM1_Beta1
KRDNELPNIYVKNNETGISYHLIFNPASETNGAIAMSVVGNSNSSIGLM
>MuM1_Beta2
KRSNNYPIYAPLCDSYIALDYCANQSKWAGIYQSGELTNMLEELLQNDVNGGWKSDFYKMYTIQENGKDQDWEISWRMYLAHAGNWIHWTQCDTGY

If one assumes the `KR` motif is the proteolytic cleaveage site, then
this Beta sub-unit is split between two units and the Alpha Sub-unit has
an extension on the C' end which isn't found in canonical K1.

=================================================

>kt;M1;Kazachstania_africana;XP_003954584.1
MRSISLFCFAFFTVVALAAFPYYDYIHLGVTTIYAYFQDDKPIAVKVAWWGSFIQSTTNVIQTGIDACEACKDNHEDSAS
LDCARAVTNLAGTLATNLLSIYVGWHYAGTPNGSLEGADPTALRKRQLRQCESTNGLYDVSCVTDWLFDHYSQPESGKWY
PIDNSLTKRDLTQPSIYLKHNETSEVYHLIFNPSSGSTGTLAIAPARIVGNSTLAKRQDLPVYSPLCTGYIALDFCANQS
KWGGFYTSGELENELNEIFANDVSGSWRADYYKMYTCEDTCDTQDWEVSFRLYYASVGKFLHWTKCDTGS

```
# SignalP-6.0	Organism: Eukarya	Timestamp: 20260401191319
# ID	Prediction	OTHER	SP(Sec/SPI)	CS Position
kt_M1_Kazachstania_africana_XP_003954584.1	SP	0.000174	0.999854	CS pos: 18-19. Pr: 0.9803
```

=================================================

>MuM1_Signal
MFFSLPIQKEIANHTIMKVNLLNLLCLTSVVSA
>MuM1_Alpha
SFPYYDTIHLGLSALYAYFEPNSPIAVKIAFWGSFVEALDCTLDKAIDVCIACEAKHEEPKWDCTRASKDLGISVVKNAISLYVGWQHAGTPNGSLEGQDTTALK
>MuM1_Gamma
krSIARHCMSDEGYDHSCVSSWLSDHYRDGMVTGWHEVSYPFVKRDNELPNIYVKNNETGISYHLIFNPASETNGAIAMSVVGNSNSSIGLM
>MuM1_Beta
krSNNYPIYAPLCDSYIALDYCANQSKWAGIYQSGELTNMLEELLQNDVNGGWKSDFYKMYTIQENGKDQDWEISWRMYLAHAGNWIHWTQCDTGY

>KaM1_signal
MRSISLFCFAFFTVVALA
>KaM1_alpha
AFPYYDYIHLGVTTIYAYFQDDKPIAVKVAWWGSFIQSTTNVIQTGIDACEACKDNHEDSASLDCARAVTNLAGTLATNLLSIYVGWHYAGTPNGSLEGADPTALR
>KaM1_gamma
krQLRQCESTNGLYDVSCVTDWLFDHYSQPESGKWYPIDNSLTKRDLTQPSIYLKHNETSEVYHLIFNPSSGSTGTLAIAPARIVGNSTLA
>KaM1_beta
krQDLPVYSPLCTGYIALDFCANQSKWGGFYTSGELENELNEIFANDVSGSWRADYYKMYTCEDTCDTQDWEVSFRLYYASVGKFLHWTKCDTGS

>SpM1Ld
MRNSTFTLNLIVLILVSSFFNHFTSG
>SpM1La
ADISEKFGKRWSTSNTYHALVLGAKYLWACYEWDQPWRIEVAWWGTMAAEDGGFIDTIGSGRNACQICLNKKEDPETDCFTAVSEVLKMSIMNAVKISIGWRAQSVVNAAIDNTSDQPL
>SpM1Lg
krSTMPYPCDDGWCLDSDNVTYSTPDLYTHAEQLYAGTDVVILTPESLTRRDSTGLETVTVMNITSGLTVDINHRIDHTGCGTVFVGPPSTIAGVNMTLTK
>SpM1Lb
rrDDPHEFPFCDGFIGVDYCSNHNSLGGIYGSGELDTMAHDLAYADSNGNNYVDFYKMYWVKDSGNEDWLTSFRTYYTNAPSSAIHWSQCDTGA

>ScM1a_delta
MTKPTQVLVRSVSILFFITLLHLVVALNDVAGPAETAPVSLLPR
>ScM1a_alpha_
EAPWYDKIWEVKDWLLQRATDGNWGKSITWGSFVASDAGVVIFGINVCKNCVGERKEDSSTDCGKQTLALLVSIFVAVTSGHHLIWGGNRPVSQSDPNGATVA
>ScM1a_gamma
rrDISTVADGDIPLDFSALNDILNEHGISILPANASQYVKRSDTAEHTTSFVVTNNYTSLHTDLIHHGNGTYTTFTTPHIPAVA
>ScM1a_beta
rrYVYPMCEHGIKASYCMALNDAMVSADGNLYGLAEKLFSEDEGQWETNYYKLYWSTGQWIMSMKFIEESIDNANNDFEGCDTGH



```{r}

# kt1 Sequences with direct alignment to MuK1

# CAL9728017.1
# CAL9731056.1
# CAL9734481.1
# CAL9734801.1
# CAL9736462.1
# CAL9737443.1
# CAL9737967.1
# CAL9737969.1
# CAN6595279.1
# CAN6598639.1
# CAN6624170.1
# CAN6671830.1
# KAK5774264.1
# KAK5780239.1
# MW248137
# XP_003671029.2
# XP_003683531.1
# XP_003684118.1
# XP_003684596.1
# XP_003954584.1
# XP_003956787.1
# XP_003959210.1
# XP_003959753.1
# XP_064713765.1

# seqkit grep -nrf MuK1.match.list ../kt1/kt1.fa > MuK1.kt1.match.fa
# grep -f MuK1.match.list ../kt1.M1_Logan.pro > MuK1.match_Logan.pro

# muscle -align MuK1.kt1.match.fa -output MuK1.kt1.match.msa.fa

```











